export let products = [
  {
    title: "Real Madrid FC Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 50,
    stock: 3,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959054/real-madrid_opwtjw.webp",
  },
  {
    title: "FC Barcelona Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 45,
    stock: 8,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/barcelona-fc_ndzu4r.webp",
  },
  {
    title: "Manchester United Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 40,
    stock: 12,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959052/man-united_sjrjpx.jpg",
  },
  {
    title: "Juventus Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 55,
    stock: 6,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959050/juventus_attey0.png",
  },
  {
    title: "Bayern Munich Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 60,
    stock: 7,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/bayern_tjmg6h.webp",
  },
  {
    title: "Liverpool Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 50,
    stock: 1,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959050/liverpool_bebbvj.webp",
  },
  {
    title: "Paris Saint-Germain Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 55,
    stock: 5,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959053/psg_pfnkdo.jpg",
  },
  {
    title: "Manchester City Home Authentic Jersey",
    description: "Home jersey season 2023-2024",
    category: "Jerseys",
    price: 45,
    stock: 10,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959051/man-city_oh7a6k.webp",
  },
  {
    title: "Tottenham Hotspur FC Scarf",
    description: "Official Tottenham Hotspur scarf",
    category: "Scarf",
    price: 20,
    stock: 10,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959055/tottenham-bufanda_fv15oo.webp",
  },
  {
    title: "Atletico de Madrid Scarf",
    description: "Official Atletico de Madrid scarf",
    category: "Scarf",
    price: 18,
    stock: 15,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/bu-atl-mad_dvlalw.jpg",
  },
  {
    title: "Inter de Milan Scarf",
    description: "Official Inter de Milan scarf",
    category: "Scarf",
    price: 22,
    stock: 12,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959050/inter-milan-bufanda_fzmd2u.jpg",
  },
  {
    title: "Borussia Dortmund Scarf",
    description: "Official Borussia Dortmund scarf",
    category: "Scarf",
    price: 25,
    stock: 9,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/bvb-bufanda_zl8msp.webp",
  },
  {
    title: "Real Madrid Home Baseball Cap",
    description: "Home baseball cap",
    category: "Hat",
    price: 20,
    stock: 5,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959054/real-madrid-gorra_fnnffc.webp",
  },
  {
    title: "Milan Away Baseball Cap",
    description: "Away baseball cap",
    category: "Hat",
    price: 18,
    stock: 7,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959053/milan-gorra_bg0xuf.jpg",
  },
  {
    title: "Chelsea FC Home Baseball Cap",
    description: "Home baseball cap",
    category: "Hat",
    price: 22,
    stock: 3,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959050/chelsea-gorra_xvbmi3.webp",
  },
  {
    title: "FC Barcelona Home Authentic Shorts",
    description: "Home shorts season 2023-2024",
    category: "Shorts",
    price: 28,
    stock: 8,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/barcelona-shorts_pkbflf.jpg",
  },
  {
    title: "Manchester United Away Authentic Shorts",
    description: "Away shorts season 2023-2024",
    category: "Shorts",
    price: 25,
    stock: 12,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959052/man-united-shorts_ewyfbu.jpg",
  },
  {
    title: "Boca Juniors Bucket Hat",
    description: "Official Boca Juniors bucket hat",
    category: "Hats",
    price: 25,
    stock: 5,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959049/boca-bucket-hat_xrn3uw.jpg",
  },
  {
    title: "Maradona Eterno Bucket Hat",
    description: "Maradona tribute bucket hat",
    category: "Hats",
    price: 25,
    stock: 5,
    img: "https://res.cloudinary.com/dcyvajngc/image/upload/v1719959053/maradona-hat_luqiqy.webp",
  },
];
