export let products = [
  {
    id: 1,
    equipo: "Real Madrid FC",
    categoria: "Camiseta",
    precio: 50,
    stock: 3,
    rutaImagen: "real-madrid.webp",
  },
  {
    id: 2,
    equipo: "FC Barcelona",
    categoria: "Camiseta",
    precio: 45,
    stock: 8,
    rutaImagen: "barcelona-fc.webp",
  },
  {
    id: 3,
    equipo: "Manchester United",
    categoria: "Camiseta",
    precio: 40,
    stock: 12,
    rutaImagen: "man-united.jpeg",
  },
  {
    id: 4,
    equipo: "Juventus",
    categoria: "Camiseta",
    precio: 55,
    stock: 6,
    rutaImagen: "juventus.png",
  },
  {
    id: 5,
    equipo: "Bayern Munich",
    categoria: "Camiseta",
    precio: 60,
    stock: 7,
    rutaImagen: "bayern.webp",
  },
  {
    id: 6,
    equipo: "Liverpool",
    categoria: "Camiseta",
    precio: 50,
    stock: 1,
    rutaImagen: "liverpool.webp",
  },
  {
    id: 7,
    equipo: "Paris Saint-Germain",
    categoria: "Camiseta",
    precio: 55,
    stock: 5,
    rutaImagen: "psg.jpeg",
  },
  {
    id: 8,
    equipo: "Manchester City",
    categoria: "Camiseta",
    precio: 45,
    stock: 10,
    rutaImagen: "man-city.webp",
  },
  {
    id: 20,
    equipo: "Tottenham Hotspur",
    categoria: "Bufanda",
    precio: 20,
    stock: 10,
    rutaImagen: "tottenham-bufanda.webp",
  },
  {
    id: 21,
    equipo: "Atletico de Madrid",
    categoria: "Bufanda",
    precio: 18,
    stock: 15,
    rutaImagen: "bu-atl-mad.jpeg",
  },
  {
    id: 22,
    equipo: "Inter de Milan",
    categoria: "Bufanda",
    precio: 22,
    stock: 12,
    rutaImagen: "inter-milan-bufanda.jpeg",
  },
  {
    id: 23,
    equipo: "Borussia Dortmund",
    categoria: "Bufanda",
    precio: 25,
    stock: 9,
    rutaImagen: "bvb-bufanda.webp",
  },
  {
    id: 30,
    equipo: "Real Madrid",
    categoria: "Gorra",
    precio: 20,
    stock: 5,
    rutaImagen: "real-madrid-gorra.webp",
  },
  {
    id: 31,
    equipo: "Milan",
    categoria: "Gorra",
    precio: 18,
    stock: 7,
    rutaImagen: "milan-gorra.jpeg",
  },
  {
    id: 32,
    equipo: "Chelsea FC",
    categoria: "Gorra",
    precio: 22,
    stock: 3,
    rutaImagen: "chelsea-gorra.webp",
  },
  {
    id: 41,
    equipo: "FC Barcelona",
    categoria: "Shorts",
    precio: 28,
    stock: 8,
    rutaImagen: "barcelona-shorts.jpeg",
  },
  {
    id: 42,
    equipo: "Manchester United",
    categoria: "Shorts",
    precio: 25,
    stock: 12,
    rutaImagen: "man-united-shorts.webp",
  },
  {
    id: 43,
    equipo: "Boca Juniors",
    categoria: "Piluso",
    precio: 25,
    stock: 5,
    rutaImagen: "boca-bucket-hat.jpeg",
  },
  {
    id: 44,
    equipo: "Maradona Eterno",
    categoria: "Piluso",
    precio: 25,
    stock: 5,
    rutaImagen: "maradona-hat.webp",
  },
];
